name: pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  main:
    name: Nx Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Get base and head commits for `nx affected`
        uses: nrwl/nx-set-shas@v4.3.0
        with:
          main-branch-name: main
      - name: Run Tests
        run: pnpm run test:pr
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run prettier
        run: pnpm run test:format
  test-react-17:
    name: 'Test React 17'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Get base and head commits for `nx affected`
        uses: nrwl/nx-set-shas@v4.3.0
        with:
          main-branch-name: main
      - name: Run Tests
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: pnpm nx affected --targets=test:lib
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: false
          REACTJS_VERSION: 17
